"use client";

import { useEffect, useState, use } from "react";
import { PRDEditor } from "@/components/editor/prd-editor";
import { Loader2, CheckCircle, FileText, Check, Sparkles, RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { VersionHistory } from "@/components/editor/version-history";
import { Button } from "@/components/ui/button";

export default function PRDPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const router = useRouter();

  const [prd, setPrd] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [isApproving, setIsApproving] = useState(false);

  useEffect(() => {
    fetchPrd();
  }, [projectId]);

  const fetchPrd = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}/prd`);
      if (res.ok) {
        const data = await res.json();
        setPrd(data.prd);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleGeneratePrd = async () => {
    setGenerating(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/prd`, { method: "POST" });
      if (res.ok) {
        // Poll for completion
        let count = 0;
        const interval = setInterval(async () => {
          count++;
          const checkRes = await fetch(`/api/projects/${projectId}/prd`);
          if (checkRes.ok) {
            const data = await checkRes.json();
            if (data.prd) {
              setPrd(data.prd);
              setGenerating(false);
              clearInterval(interval);
            }
          }
          if (count > 20) {
            setGenerating(false);
            clearInterval(interval);
          }
        }, 3000);
      } else {
        setGenerating(false);
      }
    } catch (err) {
      setGenerating(false);
    }
  };

  const handleApprove = async () => {
    setIsApproving(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/prd/approve`, { method: "POST" });
      if (res.ok) {
        router.push(`/projects/${projectId}/design`);
      }
    } finally {
      setIsApproving(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center py-20"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>;
  }

  if (!prd) {
    return (
      <div className="max-w-2xl mx-auto py-20 text-center space-y-6">
        <div className="w-16 h-16 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center mx-auto text-primary">
          <FileText className="w-8 h-8" />
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-bold text-foreground">No PRD Generated Yet</h2>
          <p className="text-sm text-muted-foreground max-w-md mx-auto">
            Click below to run the AI PRD Agent to transform extracted requirements into a comprehensive Product Requirements Document.
          </p>
        </div>
        <Button
          onClick={handleGeneratePrd}
          disabled={generating}
          className="bg-primary hover:bg-primary/90 shadow-lg shadow-primary/25 px-6"
        >
          {generating ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin mr-2" />
              Generating PRD with DeepSeek AI...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate PRD with AI
            </>
          )}
        </Button>
      </div>
    );
  }

  const initialHtml = prd.contentMarkdown || `
    <h1>${prd.content?.title || "Product Requirements Document"}</h1>
    <h2>Overview</h2>
    <p>${prd.content?.overview?.problem || ""}</p>
    <h2>Features</h2>
    <ul>
      ${(prd.content?.features || []).map((f: any) => `<li><strong>${f.title}</strong>: ${f.userStory}</li>`).join("")}
    </ul>
  `;

  return (
    <div className="max-w-6xl mx-auto space-y-6 p-8">
      <div className="flex justify-between items-center bg-card/60 p-6 rounded-2xl border border-border/60 backdrop-blur-xl">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-3">
            <FileText className="w-6 h-6 text-primary" />
            Product Requirements Document
          </h1>
          <p className="text-sm text-muted-foreground mt-1">Version {prd.version} • Generated by {prd.generatedBy}</p>
        </div>
        
        <Button
          onClick={handleApprove}
          disabled={isApproving}
          className="bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-900/20 flex items-center gap-2"
        >
          {isApproving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
          Approve PRD & Continue
        </Button>
      </div>

      <PRDEditor 
        projectId={projectId}
        initialContent={initialHtml} 
        onUpdate={(content) => {
          console.log("PRD Content updated", content.length);
        }} 
      />

      <VersionHistory 
        projectId={projectId} 
        onRestore={(versionId) => {
          console.log("Restore requested for version:", versionId);
        }} 
      />
    </div>
  );
}
