"use client";

import { useEffect, useState } from "react";
import { PRDEditor } from "@/components/editor/prd-editor";
import { Loader2, CheckCircle, FileText, Check } from "lucide-react";
import { useRouter } from "next/navigation";
import { use } from "react";

import { VersionHistory } from "@/components/editor/version-history";

export default function PRDPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const router = useRouter();

  const [prd, setPrd] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isApproving, setIsApproving] = useState(false);

  useEffect(() => {
    fetchPrd();
  }, [projectId]);

  const fetchPrd = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}/prd`);
      if (res.ok) {
        const data = await res.json();
        setPrd(data.prd);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async () => {
    setIsApproving(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/prd/approve`, { method: "POST" });
      if (res.ok) {
        router.push(`/projects/${projectId}`);
      }
    } finally {
      setIsApproving(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center py-20"><Loader2 className="w-8 h-8 animate-spin text-indigo-500" /></div>;
  }

  if (!prd) {
    return (
      <div className="max-w-4xl mx-auto py-20 text-center">
        <FileText className="w-16 h-16 text-slate-700 mx-auto mb-4" />
        <h2 className="text-xl font-bold text-white mb-2">No PRD Generated Yet</h2>
        <p className="text-slate-400">Complete the requirement analysis phase to generate a PRD.</p>
      </div>
    );
  }

  const initialHtml = prd.contentMarkdown || `
    <h1>${prd.content?.title || "Product Requirements Document"}</h1>
    <h2>Overview</h2>
    <p>${prd.content?.overview?.problem || ""}</p>
    <h2>Features</h2>
    <ul>
      ${(prd.content?.features || []).map((f: any) => `<li><strong>${f.title}</strong>: ${f.userStory}</li>`).join("")}
    </ul>
  `;

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex justify-between items-center bg-slate-900/60 p-6 rounded-2xl border border-slate-800 backdrop-blur-xl">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="w-6 h-6 text-indigo-400" />
            Product Requirements Document
          </h1>
          <p className="text-sm text-slate-400 mt-1">Version {prd.version} • Generated by {prd.generatedBy}</p>
        </div>
        
        <button
          onClick={handleApprove}
          disabled={isApproving}
          className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold rounded-xl shadow-lg shadow-emerald-900/20 flex items-center gap-2 transition-all disabled:opacity-50"
        >
          {isApproving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
          Approve PRD
        </button>
      </div>

      <PRDEditor 
        projectId={projectId}
        initialContent={initialHtml} 
        onUpdate={(content) => {
          console.log("PRD Content updated", content.length);
        }} 
      />

      <VersionHistory 
        projectId={projectId} 
        onRestore={(versionId) => {
          console.log("Restore requested for version:", versionId);
        }} 
      />
    </div>
  );
}
