"use client";

import { useEffect, useState } from "react";
import { Loader2, Server, CheckCircle, Wand2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { use } from "react";
import { ArchitectureViewer } from "@/components/architecture/architecture-viewer";
import { AIChatPanel } from "@/components/architecture/ai-chat-panel";

export default function ArchitecturePage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const router = useRouter();

  const [arch, setArch] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isApproving, setIsApproving] = useState(false);

  useEffect(() => {
    fetchArch();
  }, [projectId]);

  const fetchArch = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}/architecture`);
      if (res.ok) {
        const data = await res.json();
        if (data.architectures && data.architectures.length > 0) {
          setArch(data.architectures[0]);
        } else {
          setArch(null);
        }
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
        const res = await fetch(`/api/projects/${projectId}/architecture`, { method: "POST" });
        if (res.ok) {
            setTimeout(() => {
                fetchArch();
                setIsGenerating(false);
            }, 10000);
        } else {
            setIsGenerating(false);
        }
    } catch {
        setIsGenerating(false);
    }
  };

  const handleApprove = async () => {
    if (!arch) return;
    setIsApproving(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/architecture/${arch.id}/approve`, { method: "POST" });
      if (res.ok) {
        router.push(`/projects/${projectId}`); // Move to execution phase later
      }
    } finally {
      setIsApproving(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center py-20"><Loader2 className="w-8 h-8 animate-spin text-indigo-500" /></div>;
  }

  if (!arch) {
    return (
      <div className="max-w-4xl mx-auto py-20 text-center bg-slate-900/40 rounded-3xl border border-slate-800/50 backdrop-blur-md">
        <div className="bg-slate-800/50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6">
            <Server className="w-10 h-10 text-indigo-400" />
        </div>
        <h2 className="text-2xl font-bold text-white mb-3">No Architecture Generated</h2>
        <p className="text-slate-400 mb-8 max-w-md mx-auto">Generate a highly structured cloud architecture spec based on your PRD and approved Design.</p>
        
        <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl shadow-lg shadow-indigo-900/30 flex items-center gap-3 mx-auto transition-all disabled:opacity-50"
        >
            {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Wand2 className="w-5 h-5" />}
            {isGenerating ? "AI is Architecting..." : "Generate Architecture"}
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6 h-[85vh] flex flex-col">
      <div className="flex justify-between items-center bg-slate-900/60 p-6 rounded-2xl border border-slate-800 backdrop-blur-xl shrink-0">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <Server className="w-6 h-6 text-indigo-400" />
            System Architecture
          </h1>
          <p className="text-sm text-slate-400 mt-1">Version {arch.version} • Generated by {arch.generatedBy}</p>
        </div>
        
        <button
          onClick={handleApprove}
          disabled={isApproving}
          className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold rounded-xl shadow-lg shadow-emerald-900/20 flex items-center gap-2 transition-all disabled:opacity-50"
        >
          {isApproving ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle className="w-4 h-4" />}
          Approve Architecture
        </button>
      </div>

      <div className="flex-1 min-h-0 flex gap-6">
          <div className="flex-1 bg-slate-950 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl flex flex-col">
              <ArchitectureViewer spec={arch.architectureSpec} />
          </div>
          
          <AIChatPanel projectId={projectId} currentArch={arch.architectureSpec} onUpdated={fetchArch} />
      </div>
    </div>
  );
}
