/**
 * Per-project compose spec (Phase 14 / BE-9): a pure, data-only description
 * of the two containers a project needs — the app runtime and its
 * database — with resource limits, labels, and env references. This file
 * never touches Docker or the filesystem; `manager.ts` turns a `ComposeSpec`
 * into real dockerode calls, and `serializeComposeYaml` turns it into a
 * `docker-compose.yml` for `scripts/provision-project.ts`'s manual/dev path.
 *
 * Resource limits are not optional (Phase 14 exit criteria) — an unbounded
 * generated app can take down the host for every other project.
 */

export const MANAGED_LABEL = "com.kairopro.managed";
export const PROJECT_LABEL = "com.kairopro.project-id";
export const ROLE_LABEL = "com.kairopro.role";

export const APP_CPU_LIMIT = 1; // 1 vCPU
export const APP_MEMORY_LIMIT_MB = 512;
export const DB_CPU_LIMIT = 0.5;
export const DB_MEMORY_LIMIT_MB = 256;

export const DB_IMAGE = "postgres:18-alpine";
export const DB_INTERNAL_PORT = 5432;
export const DB_USER = "app";
export const DB_PASSWORD = "app";
export const DB_NAME = "app";
/** The db service's DNS name on the project's own network. */
export const DB_HOSTNAME = "db";

export interface ComposeServiceLimits {
  cpus: number;
  memoryMb: number;
}

export interface ComposeAppService {
  image: string;
  labels: Record<string, string>;
  limits: ComposeServiceLimits;
  environment: Record<string, string>;
  /** Port the app listens on inside the container. */
  port: number;
  network: string;
  dependsOnHealthyDb: true;
}

export interface ComposeDbService {
  image: string;
  labels: Record<string, string>;
  limits: ComposeServiceLimits;
  environment: Record<string, string>;
  volumeName: string;
  network: string;
  healthcheck: string[];
}

export interface ComposeSpec {
  projectId: string;
  networkName: string;
  app: ComposeAppService;
  db: ComposeDbService;
}

export interface BuildComposeSpecInput {
  projectId: string;
  appImage: string;
  /** Extra environment for the app container — decrypted credentials,
   * injected by the caller (Phase 12's `putCredential` flow). Never logged. */
  appEnv?: Record<string, string>;
  port?: number;
}

function baseLabels(projectId: string, role: "app" | "db"): Record<string, string> {
  return {
    [MANAGED_LABEL]: "true",
    [PROJECT_LABEL]: projectId,
    [ROLE_LABEL]: role,
  };
}

/** The project's own isolated network name — never shared across projects. */
export function networkNameFor(projectId: string): string {
  return `kairopro-net-${projectId}`;
}

function volumeNameFor(projectId: string): string {
  return `kairopro-db-${projectId}`;
}

/** The app's connection string to its own db container — always the same
 * shape, since each project's db lives alone on that project's own
 * isolated network under the fixed alias `db`. */
export function databaseUrlFor(): string {
  return `postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_INTERNAL_PORT}/${DB_NAME}`;
}

/**
 * Builds the per-project compose spec. Pure — no I/O, no Docker client —
 * so it's testable against a fixture without a daemon.
 */
export function buildComposeSpec(input: BuildComposeSpecInput): ComposeSpec {
  const network = networkNameFor(input.projectId);

  return {
    projectId: input.projectId,
    networkName: network,
    app: {
      image: input.appImage,
      labels: baseLabels(input.projectId, "app"),
      limits: { cpus: APP_CPU_LIMIT, memoryMb: APP_MEMORY_LIMIT_MB },
      environment: {
        ...input.appEnv,
        DATABASE_URL: databaseUrlFor(),
      },
      port: input.port ?? 3000,
      network,
      dependsOnHealthyDb: true,
    },
    db: {
      image: DB_IMAGE,
      labels: baseLabels(input.projectId, "db"),
      limits: { cpus: DB_CPU_LIMIT, memoryMb: DB_MEMORY_LIMIT_MB },
      environment: {
        POSTGRES_USER: DB_USER,
        POSTGRES_PASSWORD: DB_PASSWORD,
        POSTGRES_DB: DB_NAME,
      },
      volumeName: volumeNameFor(input.projectId),
      network,
      healthcheck: ["CMD-SHELL", `pg_isready -U ${DB_USER} -d ${DB_NAME}`],
    },
  };
}

/** A `docker-compose.yml` rendering of the spec — for manual/dev use
 * (`scripts/provision-project.ts`) only. The real provisioning path
 * (`manager.ts`) never writes this to disk, so decrypted credentials in
 * `appEnv` never land in a file there. */
export function serializeComposeYaml(spec: ComposeSpec): string {
  const envLines = (env: Record<string, string>) =>
    Object.entries(env)
      .map(([key, value]) => `      ${key}: ${JSON.stringify(value)}`)
      .join("\n");

  return `# Generated by compose.ts — for manual/dev use only.
name: kairopro-${spec.projectId}

services:
  app:
    image: ${spec.app.image}
    labels:
${Object.entries(spec.app.labels)
  .map(([k, v]) => `      ${k}: ${JSON.stringify(v)}`)
  .join("\n")}
    deploy:
      resources:
        limits:
          cpus: "${spec.app.limits.cpus}"
          memory: ${spec.app.limits.memoryMb}M
    environment:
${envLines(spec.app.environment)}
    ports:
      - "${spec.app.port}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ${spec.networkName}

  db:
    image: ${spec.db.image}
    labels:
${Object.entries(spec.db.labels)
  .map(([k, v]) => `      ${k}: ${JSON.stringify(v)}`)
  .join("\n")}
    deploy:
      resources:
        limits:
          cpus: "${spec.db.limits.cpus}"
          memory: ${spec.db.limits.memoryMb}M
    environment:
${envLines(spec.db.environment)}
    volumes:
      - ${spec.db.volumeName}:/var/lib/postgresql
    healthcheck:
      test: ${JSON.stringify(spec.db.healthcheck)}
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - ${spec.networkName}

networks:
  ${spec.networkName}:
    name: ${spec.networkName}

volumes:
  ${spec.db.volumeName}:
    name: ${spec.db.volumeName}
`;
}
